version: '3.5'

networks:
  rmoff_kafka:
    name: rmoff_kafka
    driver: bridge
    ipam:
      driver: default

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper
    networks:
      - rmoff_kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  broker:
    image: confluentinc/cp-kafka:5.5.0
    container_name: broker
    networks:
      - rmoff_kafka
    depends_on:
      - zookeeper
    ports:
      - '19092:19092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "client:1:1,result:1:1:compact"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  classifier:
    container_name: python_kafka_test_classifier
    depends_on:
      - broker
    networks:
      - rmoff_kafka
    build:
      context: .
      dockerfile: Dockerfile_classifier
      args:
        MOM: kafka

  client:
    container_name: python_kafka_test_client
    networks:
      - rmoff_kafka
    depends_on:
      - broker
    build:
      context: .
      dockerfile: Dockerfile_client
      args:
        MOM: kafka

  classifier2:
    container_name: python_pubsub_test_classifier
    depends_on:
      - broker
    networks:
      - rmoff_kafka
    build:
      context: .
      dockerfile: Dockerfile_classifier
      args:
        MOM: pubsub

  client2:
    container_name: python_pubsub_test_client
    networks:
      - rmoff_kafka
    depends_on:
      - broker
    build:
      context: .
      dockerfile: Dockerfile_client
      args:
        MOM: pubsub